# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import re
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(338, 523)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-calculator-1000.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setWindowOpacity(1.0)
        mainWindow.setStyleSheet("background-color: rgb(249, 249, 249);\n"
                                 "")
        mainWindow.setIconSize(QtCore.QSize(200, 200))
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # btn 0
        self.btn_0 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("0"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_0.setFont(font)
        self.btn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_0.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_0.setObjectName("btn_0")
        self.gridLayout_2.addWidget(self.btn_0, 6, 1, 1, 1)

        # btn 1
        self.btn_1 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("1"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_1.setFont(font)
        self.btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_1.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_1.setObjectName("btn_1")
        self.gridLayout_2.addWidget(self.btn_1, 5, 0, 1, 1)

        # btn 2
        self.btn_2 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("2"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_2.setFont(font)
        self.btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_2.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_2.setObjectName("btn_2")
        self.gridLayout_2.addWidget(self.btn_2, 5, 1, 1, 1)

        # btn 3
        self.btn_3 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("3"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_3.setFont(font)
        self.btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_3.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_3.setObjectName("btn_3")
        self.gridLayout_2.addWidget(self.btn_3, 5, 2, 1, 1)

        # btn 4
        self.btn_4 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("4"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_4.setFont(font)
        self.btn_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_4.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_4.setObjectName("btn_4")
        self.gridLayout_2.addWidget(self.btn_4, 4, 0, 1, 1)
        # btn 5
        self.btn_5 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("5"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_5.setFont(font)
        self.btn_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_5.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_5.setObjectName("btn_5")
        self.gridLayout_2.addWidget(self.btn_5, 4, 1, 1, 1)

        # btn 6
        self.btn_6 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("6"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_6.setFont(font)
        self.btn_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_6.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_6.setObjectName("btn_6")
        self.gridLayout_2.addWidget(self.btn_6, 4, 2, 1, 1)

        # btn 7
        self.btn_7 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("7"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_7.setFont(font)
        self.btn_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_7.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_7.setObjectName("btn_7")
        self.gridLayout_2.addWidget(self.btn_7, 3, 0, 1, 1)

        # btn 8
        self.btn_8 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("8"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_8.setFont(font)
        self.btn_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_8.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_8.setObjectName("btn_8")
        self.gridLayout_2.addWidget(self.btn_8, 3, 1, 1, 1)

        # btn 9
        self.btn_9 = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("9"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_9.setFont(font)
        self.btn_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_9.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "}\n"
                                 "")
        self.btn_9.setObjectName("btn_9")
        self.gridLayout_2.addWidget(self.btn_9, 3, 2, 1, 1)

        # btn invert
        self.btn_inv = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.invert())
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_inv.sizePolicy().hasHeightForWidth())
        self.btn_inv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_inv.setFont(font)
        self.btn_inv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_inv.setStyleSheet("QPushButton{\n"
                                   "background-color: rgb(247, 247, 247);\n"
                                   "border-radius: 36px;\n"
                                   "}\n"
                                   "")
        self.btn_inv.setObjectName("btn_inv")
        self.gridLayout_2.addWidget(self.btn_inv, 6, 0, 1, 1)

        # btn multiplication
        self.btn_mul = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("*"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_mul.sizePolicy().hasHeightForWidth())
        self.btn_mul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_mul.setFont(font)
        self.btn_mul.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mul.setStyleSheet("QPushButton{\n"
                                   "background-color: rgb(247, 247, 247);\n"
                                   "border-radius: 36px;\n"
                                   "    color: rgb(207, 112, 114);\n"
                                   "}")
        self.btn_mul.setObjectName("btn_mul")
        self.gridLayout_2.addWidget(self.btn_mul, 4, 3, 1, 1)

        # btn division
        self.btn_div = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("/"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_div.sizePolicy().hasHeightForWidth())
        self.btn_div.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_div.setFont(font)
        self.btn_div.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_div.setStyleSheet("QPushButton{\n"
                                   "background-color: rgb(247, 247, 247);\n"
                                   "border-radius: 36px;\n"
                                   "    color: rgb(207, 112, 114);\n"
                                   "}")
        self.btn_div.setObjectName("btn_div")
        self.gridLayout_2.addWidget(self.btn_div, 5, 3, 1, 1)

        # btn plus
        self.btn_plus = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("+"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_plus.sizePolicy().hasHeightForWidth())
        self.btn_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_plus.setFont(font)
        self.btn_plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_plus.setStyleSheet("QPushButton{\n"
                                    "background-color: rgb(247, 247, 247);\n"
                                    "border-radius: 36px;\n"
                                    "    color: rgb(207, 112, 114);\n"
                                    "}")
        self.btn_plus.setObjectName("btn_plus")
        self.gridLayout_2.addWidget(self.btn_plus, 2, 3, 1, 1)

        # btn sub
        self.btn_sub = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press("-"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_sub.sizePolicy().hasHeightForWidth())
        self.btn_sub.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_sub.setFont(font)
        self.btn_sub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sub.setStyleSheet("QPushButton{\n"
                                   "background-color: rgb(247, 247, 247);\n"
                                   "border-radius: 36px;\n"
                                   "    color: rgb(207, 112, 114);\n"
                                   "}")
        self.btn_sub.setObjectName("btn_sub")
        self.gridLayout_2.addWidget(self.btn_sub, 3, 3, 1, 1)

        # btn percentage
        self.perct = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.perc("%"))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.perct.sizePolicy().hasHeightForWidth())
        self.perct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.perct.setFont(font)
        self.perct.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.perct.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "color: rgb(118, 227, 209);\n"
                                 "}\n"
                                 "")
        self.perct.setObjectName("perct")
        self.gridLayout_2.addWidget(self.perct, 2, 0, 1, 1)

        # btn dot
        self.btn_dot = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.dot())
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_dot.sizePolicy().hasHeightForWidth())
        self.btn_dot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_dot.setFont(font)
        self.btn_dot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dot.setStyleSheet("QPushButton{\n"
                                   "background-color: rgb(247, 247, 247);\n"
                                   "border-radius: 36px;\n"
                                   "}\n"
                                   "")
        self.btn_dot.setObjectName("btn_dot")
        self.gridLayout_2.addWidget(self.btn_dot, 6, 2, 1, 1)

        # btn equal
        self.btn_equal = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.eval())
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_equal.sizePolicy().hasHeightForWidth())
        self.btn_equal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_equal.setFont(font)
        self.btn_equal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_equal.setStyleSheet("QPushButton{\n"
                                     "background-color: rgb(247, 247, 247);\n"
                                     "border-radius: 36px;\n"
                                     "    color: rgb(207, 112, 114);\n"
                                     "}")
        self.btn_equal.setObjectName("btn_equal")
        self.gridLayout_2.addWidget(self.btn_equal, 6, 3, 1, 1)

        # btn clear the last number or operator
        self.clr_lst = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.clear_lst())
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.clr_lst.sizePolicy().hasHeightForWidth())
        self.clr_lst.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clr_lst.setFont(font)
        self.clr_lst.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clr_lst.setStyleSheet("QPushButton{\n"
                                   "background-color: rgb(247, 247, 247);\n"
                                   "border-radius: 36px;\n"
                                   "color: rgb(118, 227, 209);\n"
                                   "}\n"
                                   "")
        self.clr_lst.setObjectName("clr_lst")
        self.gridLayout_2.addWidget(self.clr_lst, 2, 1, 1, 1)

        # clear
        self.clear = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.clr())
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.clear.setFont(font)
        self.clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear.setStyleSheet("QPushButton{\n"
                                 "background-color: rgb(247, 247, 247);\n"
                                 "border-radius: 36px;\n"
                                 "color: rgb(118, 227, 209);\n"
                                 "}\n"
                                 "")
        self.clear.setObjectName("clear")
        self.gridLayout_2.addWidget(self.clear, 2, 2, 1, 1)

        # Result
        self.result = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.result.sizePolicy().hasHeightForWidth())
        self.result.setSizePolicy(sizePolicy)
        self.result.setMinimumSize(QtCore.QSize(0, 72))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.result.setFont(font)
        self.result.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.result.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.gridLayout_2.addWidget(self.result, 0, 0, 1, 4)

        # expression
        self.expression = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.expression.sizePolicy().hasHeightForWidth())
        self.expression.setSizePolicy(sizePolicy)
        self.expression.setMinimumSize(QtCore.QSize(0, 30))
        self.expression.setMaximumSize(QtCore.QSize(16777215, 30))
        self.expression.setFrameShadow(QtWidgets.QFrame.Plain)
        self.expression.setText("")
        self.expression.setTextFormat(QtCore.Qt.AutoText)
        self.expression.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.expression.setObjectName("expression")
        self.gridLayout_2.addWidget(self.expression, 1, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout_2)
        mainWindow.setCentralWidget(self.centralwidget)

        # menu bar
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 21))
        self.menubar.setStyleSheet("\n"
                                   "background-color: rgb(245, 243, 243);")
        self.menubar.setObjectName("menubar")
        self.menutools = QtWidgets.QMenu(self.menubar)
        self.menutools.setStyleSheet("QPushButton{\n"
                                     "    background-color: rgb(223, 223, 223);\n"
                                     "}")
        self.menutools.setObjectName("menutools")
        self.menutheme = QtWidgets.QMenu(self.menubar)
        self.menutheme.setObjectName("menutheme")
        mainWindow.setMenuBar(self.menubar)
        self.actionBinary = QtWidgets.QAction(mainWindow)
        self.actionBinary.setObjectName("actionBinary")
        self.actionDark = QtWidgets.QAction(mainWindow)
        self.actionDark.setObjectName("actionDark")
        self.menutools.addAction(self.actionBinary)
        self.menutheme.addAction(self.actionDark)
        self.menubar.addAction(self.menutools.menuAction())
        self.menubar.addAction(self.menutheme.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def perc(self, sym):
        result = self.result.text()
        text = int(result)
        screen = text/100
        self.result.setText(f"{screen}")

    def dot(self):
        result = self.result.text()
        num = re.split("\+|-|/|\*", result)

        if result[:-1] == ".":
            exit
        elif "." in num[-1]:
            exit
        elif "." in result[-1]:
            exit
        else:
            if result[-1] not in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]:
                if result == "0":
                    self.result.setText("0.")
                else:
                    self.result.setText(f"{self.result.text()}0.")
            else:
                self.result.setText(f"{self.result.text()}.")

    def clear_lst(self):
        screen = self.result.text()
        screen = screen[:-1]
        self.result.setText(screen)
        self.expression.setText(screen)

    def clr(self):
        self.result.setText("0")
        self.expression.setText("0")

    def press(self, num):
        if self.result.text() == "0":
            self.result.setText(f"{num}")
        else:
            self.expression.setText(f"{self.result.text()}{num}")
            self.result.setText(f"{self.result.text()}{num}")

    def eval(self):
        try:
            result = self.result.text()
            if result[:-1] == "%":
                perc(num)
            result = str(result)
            self.expression.setText(result)
            self.result.setText(str(eval(result)))
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("You cannot Divide any number by 0")
            msg.setWindowTitle("ZeroDivisionERROR")
            msg.setStandardButtons(QMessageBox.Ok)
            retval = msg.exec_()
            self.result.setText(result[:-1])
            self.expression.setText(result[:-1])

    def invert(self):
        if "-" in self.result.text():
            screen = self.result.text()
            screen = screen[1:]
            self.result.setText(screen)
            self.expression.setText(screen)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Calculator"))
        self.btn_5.setText(_translate("mainWindow", "5"))
        self.btn_5.setShortcut(_translate("mainWindow", "5"))
        self.result.setText(_translate("mainWindow", "0"))
        self.btn_7.setText(_translate("mainWindow", "7"))
        self.btn_7.setShortcut(_translate("mainWindow", "7"))
        self.btn_0.setText(_translate("mainWindow", "0"))
        self.btn_0.setShortcut(_translate("mainWindow", "0"))
        self.clear.setText(_translate("mainWindow", "C"))
        self.clear.setShortcut(_translate("mainWindow", "Ctrl+Shift+C, Del"))
        self.btn_inv.setText(_translate("mainWindow", "+ / -"))
        self.btn_inv.setShortcut(_translate("mainWindow", "Ctrl+I"))
        self.btn_9.setText(_translate("mainWindow", "9"))
        self.btn_9.setShortcut(_translate("mainWindow", "9"))
        self.btn_8.setText(_translate("mainWindow", "8"))
        self.btn_8.setShortcut(_translate("mainWindow", "8"))
        self.btn_6.setText(_translate("mainWindow", "6"))
        self.btn_6.setShortcut(_translate("mainWindow", "6"))
        self.btn_3.setText(_translate("mainWindow", "3"))
        self.btn_3.setShortcut(_translate("mainWindow", "3"))
        self.btn_mul.setText(_translate("mainWindow", "x"))
        self.btn_mul.setShortcut(_translate("mainWindow", "*"))
        self.btn_div.setText(_translate("mainWindow", "÷"))
        self.btn_div.setShortcut(_translate("mainWindow", "/"))
        self.clr_lst.setText(_translate("mainWindow", "<<"))
        self.clr_lst.setShortcut(_translate("mainWindow", "Backspace"))
        self.btn_plus.setText(_translate("mainWindow", "+"))
        self.btn_plus.setShortcut(_translate("mainWindow", "+"))
        self.btn_4.setText(_translate("mainWindow", "4"))
        self.btn_4.setShortcut(_translate("mainWindow", "4"))
        self.btn_sub.setText(_translate("mainWindow", "-"))
        self.btn_sub.setShortcut(_translate("mainWindow", "-"))
        self.btn_1.setText(_translate("mainWindow", "1"))
        self.btn_1.setShortcut(_translate("mainWindow", "1"))
        self.btn_2.setText(_translate("mainWindow", "2"))
        self.btn_2.setShortcut(_translate("mainWindow", "2"))
        self.perct.setText(_translate("mainWindow", "%"))
        self.perct.setShortcut(_translate("mainWindow", "%"))
        self.btn_dot.setText(_translate("mainWindow", "."))
        self.btn_dot.setShortcut(_translate("mainWindow", "."))
        self.btn_equal.setText(_translate("mainWindow", "="))
        self.btn_equal.setShortcut(_translate("mainWindow", "Return"))
        self.menutools.setTitle(_translate("mainWindow", "Tools"))
        self.menutheme.setTitle(_translate("mainWindow", "Theme"))
        self.actionBinary.setText(_translate("mainWindow", "Binary"))
        self.actionBinary.setShortcut(_translate("mainWindow", "Ctrl+B"))
        self.actionDark.setText(_translate("mainWindow", "Dark"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
